version: '1.0'

services:
  react-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production # ya development, jo chahiye wo rakho
    volumes:
      - .:/app
    labels:
      - subdomain=te.workbrink.com
      - websiteName=travelease-frontend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3004" ]
      interval: 30s
      timeout: 10s
      retries: 3
